Basic record implementation
NoobDevTv/VaVare pull request #7
Opened 2021-12-20 17:39 UTC by jvbsl

* Added records and record struct builder
* Added record parameters(and properties)
* Added tests for said implementations
* Updated Microsoft.CodeAnalysis for record struct compatibility
NOTE: XML summaries for parameters are not taken into account

2021-12-20 19:33 UTC, Gallimathias requested changes

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.Build().ToString().Contains("TestRecord"));
```suggestion
            Assert.That(RecordBuilder.Build().ToString().Contains("TestRecord"), Is.True);
```

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.Build().ToString().Contains("TestRecord"));
Das ist doch genau das gleiche wie Build_WhenGivenRecordName_CodeShouldContainRecordName()?

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.Build().ToString().Contains("MyNamespace"));
```suggestion
            Assert.That(RecordBuilder.Build().ToString().Contains("MyNamespace"), Is.True);
```

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.WithFields(new Field("myField", typeof(int), new List<Modifiers>() { Modifiers.Public})) .Build().ToString().Contains("publicintmyField;"));
```suggestion
            var field = new Field("myField", typeof(int), new List<Modifiers>() { Modifiers.Public });
            Assert.That(RecordBuilder.WithFields(field).Build().ToString().Contains("publicintmyField;"), Is.True);
```

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.WithAttributes(new Attribute("MyAttribute")).Build().ToString().Contains("[MyAttribute]"));
```suggestion
            Assert.That(RecordBuilder.WithAttributes(new Attribute("MyAttribute")).Build().ToString().Contains("[MyAttribute]"), Is.True);
```

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.WithParameterList(new Parameter("Bbq", typeof(int)), new Parameter("Foo", typeof(string))).Build().ToString().Contains("TestRecord(intBbq,stringFoo)"));
```suggestion
            var parameterA = new Parameter("Bbq", typeof(int)).Build().ToString().Contains("TestRecord(intBbq)");
            Assert.That(RecordBuilder.WithParameterList(parameterA), Is.True);
            var parameterB = new Parameter("Bbq", typeof(int)), new Parameter("Foo", typeof(string));
            Assert.That(RecordBuilder.WithParameterList(parameterB).Build().ToString().Contains("TestRecord(intBbq,stringFoo)"), Is.True);

```

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.WithParameterList(new Parameter("Bbq", typeof(int)), new Parameter("Foo", typeof(string))).Build().ToString().Contains("TestRecord(intBbq,stringFoo)"));
GitHub mag die Formatierung nicht

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.WithProperties(new AutoProperty("MyProperty", typeof(int), PropertyTypes.GetAndSet)).Build().ToString().Contains("intMyProperty{get;set;}"));
```suggestion
            Assert.That(RecordBuilder.WithProperties(new AutoProperty("MyProperty", typeof(int), PropertyTypes.GetAndSet)).Build().ToString().Contains("intMyProperty{get;set;}"), Is.True);
```

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +            Assert.IsTrue(RecordBuilder.ThatInheritFrom(typeof(int)).Build().ToString().Contains("TestRecord:int"));
Fühle hier die gleichen Suggestions :D

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare.Tests/Builders/RecordBuilderBaseTests.cs
> +        public void Build_WhenGivenRecordName_CodeShouldContainRecordName()
Vom Namen her finde ich es immer Besser wenn man eine ist Behauptung aufstellt und nicht Sollte verwendet. Der RecordName ist enthalten. Weil bei Grün ist das so und wenns fehlschlägt ist das nicht so ^^

2021-12-20 19:33 UTC, Gallimathias commented on src/VaVare/VaVare.csproj
> +    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.1.0-1.final" />
Das müssen wir mal checken, dass es hier nirgends zu Konflikten kommt. Final klingt nach Preview?

2021-12-20 21:40 UTC, susch19 submitted a review, later dismissed

2021-12-21 10:39 UTC, susch19 approved these changes

2021-12-21 19:01 UTC, Gallimathias approved these changes

2021-12-21 19:03 UTC, merged